--- #YAML:1.0
name:               re-engine-Plugin
version:            0.08
abstract:           API to write custom regex engines
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    perl:      5.01
    XSLoader:  0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=re-engine-Plugin
    homepage:    http://search.cpan.org/dist/re-engine-Plugin/
    license:     http://dev.perl.org/licenses/
    repository:  http://git.profvince.com/?p=perl%2Fmodules%2Fre-engine-Plugin.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
