abstract: Regular Expression engine API
author: "\xC3\x86var Arnfj\xC3\xB6r\xC3\xB0 Bjarmason <avar@cpan.org>"
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: re-engine-Plugin
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.9.5
tests: t/*.t
